kind: pipeline
type: docker
name: sonar

platform:
  arch: arm64

steps:
  - name: compile
    image: maven:3.9.5
    commands:
      - mvn compile
  - name: code-analysis
    image: spookyless/sonarqube-scanner
    settings:
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token
      sonar_key:
        from_secret: sonar_key
      sonar_name:
        from_secret: sonar_name
      binaries: "./target/classes"
---
kind: pipeline
type: docker
name: tests

platform:
  arch: arm64

steps:
  - name: test
    image: maven:3.9.5
    commands:
      - mvn test